import { mkdir, writeFile } from 'fs/promises'
import { join } from 'path'
import { app, BrowserWindow } from 'electron'

export interface SavedReportFiles {
  markdownPath: string
  pdfPath: string
}

export class ReportFileService {
  async saveReportArtifacts(sessionId: string, title: string, markdown: string): Promise<SavedReportFiles> {
    const outputDir = join(app.getPath('documents'), 'AIrevtool', 'Reports', sessionId)
    await mkdir(outputDir, { recursive: true })

    const fileBaseName = `${this.timestampPrefix()}-${sanitizeFileName(title || 'report')}`
    const markdownPath = join(outputDir, `${fileBaseName}.md`)
    const pdfPath = join(outputDir, `${fileBaseName}.pdf`)

    await writeFile(markdownPath, markdown, 'utf8')

    const pdfWindow = new BrowserWindow({
      show: false,
      webPreferences: {
        sandbox: true,
      },
    })

    try {
      const html = this.toPrintableHtml(title, markdown)
      await pdfWindow.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(html)}`)
      const pdfBuffer = await pdfWindow.webContents.printToPDF({
        printBackground: true,
        pageSize: 'A4',
        preferCSSPageSize: true,
      })
      await writeFile(pdfPath, pdfBuffer)
    } finally {
      pdfWindow.destroy()
    }

    return { markdownPath, pdfPath }
  }

  private timestampPrefix(): string {
    const now = new Date()
    const pad = (value: number) => String(value).padStart(2, '0')
    return `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}-${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`
  }

  private toPrintableHtml(title: string, markdown: string): string {
    const escapedTitle = escapeHtml(title)
    const escapedBody = escapeHtml(markdown)
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>${escapedTitle}</title>
  <style>
    @page { size: A4; margin: 18mm; }
    body {
      font-family: 'Segoe UI', Arial, sans-serif;
      color: #111827;
      background: #ffffff;
      margin: 0;
    }
    h1 {
      font-size: 20px;
      margin: 0 0 12px 0;
      color: #0f172a;
    }
    .meta {
      margin-bottom: 16px;
      color: #475569;
      font-size: 12px;
    }
    pre {
      white-space: pre-wrap;
      word-break: break-word;
      font-family: 'Cascadia Code', Consolas, monospace;
      font-size: 11px;
      line-height: 1.55;
      margin: 0;
    }
  </style>
</head>
<body>
  <h1>${escapedTitle}</h1>
  <div class="meta">Generated by AIrevtool</div>
  <pre>${escapedBody}</pre>
</body>
</html>`
  }
}

function sanitizeFileName(value: string): string {
  return value
    .replace(/[<>:"/\\|?*\x00-\x1F]/g, '-')
    .replace(/\s+/g, '_')
    .replace(/_+/g, '_')
    .slice(0, 120)
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}